### ISSUE TITLE
User\Documents\WindowsPowerShell

### ISSUE THREAD

**Issue by DavidHazeldenUK** [jayharris/dotfiles-windows#24]
The files that get copied there, are they supposed to auto execute?
As I have to do them manually?

I put the extra.ps1 in the folder root, but it didn't get used, is it in the wrong place?

Thanks for your hard work, and sorry for the stupid question.

Dave

**Comment by jayharris** [comment]
If you run through the bootstrap commands in the Readme, they will get copied into your Powershell profile directory (`~\Documents\WindowsPowerShell\`). This is also where `extra.ps1` should go.
